### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by Leo63963** [starkgate/tracking_wo_bnw#1]
Hi ! @starkgate 
I replace the 'datasets' file with the original 'datasets' file from the Tracktor, and test MOT17 datasets. It looks that data loading works well, but another bug happened:
Traceback (most recent call last):
  File "experiments/scripts/test_tracktor.py", line 106, in <module>
    tracker.step(frame)
  File "/home/mmdetection/tracking_wo_bnw/src/tracktor/tracker.py", line 259, in step
    blob['img']['filename'] = blob['img_path'][1]
IndexError: list index out of range
I am trying to debug, and if you have any idea, please let me know.
Many thanks.

**Comment by Leo63963** [comment]
Hi @starkgate 
I think I have figured the problem out, which is caused by the difference of our gt.txt.
Anther bug:

1. 

In the model.py: detections, trans_img = inference_detector(self.model, img['im_path'][0], workaround=True)
It turns out with a TypeError:
TypeError: inference_detector() got an unexpected keyword argument 'workaround'

2. 

And if I use: detections, trans_img = inference_detector(self.model, img['im_path'][0])
It turns out:
Traceback (most recent call last):
  File "experiments/scripts/test_tracktor.py", line 106, in <module>
    tracker.step(frame)
  File "/home/mmdetection/tracking_wo_bnw/src/tracktor/tracker.py", line 266, in step
    detections, img = self.obj_detect.detect(blob['img'])
  File "/home/mmdetection/tracking_wo_bnw/src/tracktor/model.py", line 14, in detect
    detections, trans_img = inference_detector(self.model, img['im_path'][0])
ValueError: not enough values to unpack (expected 2, got 1)

3. 
I refer to the inference_detector in mmdetection, it should be fine with two arguments, which are mode & img.

Could you please tell me what was wrong?

Many thanks.

**Comment by starkgate** [comment]
Right, forgot to document that. I patched mmdetection, the reason for that is that it doesn't behave in the same way torchvision does. Tracktor needs to store the images transformed by the testing pipeline and these transformed images are not returned by mmdetection's `inference_detector` function by default. I pushed a fix, the patch is now directly in Tracktor's code.

**Comment by Leo63963** [comment]
Hi ! Thanks for the update. 
Now the code working well. Just in case someone need to use the code to test MOT17Det, there are two bugs about dimensions happened to me.

1. On Model.py, 
        line 74: pred_boxes = predictions[0][0][:, :4]
        line 75: pred_scores = predictions[0][0][:, 4]
    Maybe it should be         
         pred_boxes = predictions[0][:, :4]
         pred_scores = predictions[0][:, 4]
 
2. On tracker.py,
        line 266: boxes = detections[0][:,:4]
	line 267: scores = detections[0][:,4]
   Maybe it should be 
                 boxes = detections[:,:4]
                 scores = detections[:,4]
    It works for me.

3. Plus, when I test on MOT17Det, another bug happened: 
    ValueError: tile cannot extend outside image
    It seems the detection bbox is outside of the image, and makes the tracking process stopped.
    Do you have any idea about it?
    Many thanks.

**Comment by Leo63963** [comment]
Hi ! @starkgate 
Just add more details of bug I encountered.
With **_custom_mmdetection_inference_detector_**, the modified version of inference_detector, the code is working well.
I tested on MOT17Det, the MOT17-02 works well, and got the tracking results.
However, when teseted on MOT17-05, the tracking process stopped with a ValueError:

Traceback (most recent call last):
  File "experiments/scripts/test_tracktor.py", line 106, in <module>
    tracker.step(frame)
  File "/home/lee/Detection/mmdetection/tracking_wo_bnw/src/tracktor/tracker.py", line 311, in step
    new_features = self.get_appearances(blob)
  File "/home/lee/Detection/mmdetection/tracking_wo_bnw/src/tracktor/tracker.py", line 186, in get_appearances
    new_features = self.reid_network.test_rois(blob, self.get_pos()).data
  File "/home/lee/Detection/mmdetection/tracking_wo_bnw/src/tracktor/reid/resnet.py", line 68, in test_rois
    x = self.build_crops(image, rois)
  File "/home/lee/Detection/mmdetection/tracking_wo_bnw/src/tracktor/reid/resnet.py", line 108, in build_crops
    im = trans(im)
  File "/home/lee/anaconda3/envs/mdt/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/home/lee/anaconda3/envs/mdt/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 172, in __call__
    return F.to_pil_image(pic, self.mode)
  File "/home/lee/anaconda3/envs/mdt/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 259, in to_pil_image
    return Image.fromarray(npimg, mode=mode)
  File "/home/lee/anaconda3/envs/mdt/lib/python3.7/site-packages/PIL/Image.py", line 2770, in fromarray
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
  File "/home/lee/anaconda3/envs/mdt/lib/python3.7/site-packages/PIL/Image.py", line 2710, in frombuffer
    return frombytes(mode, size, data, decoder_name, args)
  File "/home/lee/anaconda3/envs/mdt/lib/python3.7/site-packages/PIL/Image.py", line 2650, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/home/lee/anaconda3/envs/mdt/lib/python3.7/site-packages/PIL/Image.py", line 797, in frombytes
    d.setimage(self.im)
ValueError: tile cannot extend outside image

In my perspective, if the detection bbox is outside of the image, the mmdetecion will crop the image to make bbox inside of the bbox. But from ValueError, it seems the bug is caused by the bbox outside of image.
Do you have any idea ahout it?
Many thanks.

**Comment by Leo63963** [comment]
Hi ! @starkgate 
Update about the bug.
It looks that the bugs happened with MOT17-05, because that the size of images on MOT17-05 is 640 * 480, and by resizing, 
            r = r.cpu() * ratio     #  line 92, tracking_wo_bnw/src/tracktor/reid/resnet.py
the size become 1088 * 800, which is larger than the original image.
The code works well with other sequence, which are all of size 1920 * 1080.
However, if running  without resize to 1088 * 800, the tracking process would still shut down with same VauleError as before.

**Comment by Leo63963** [comment]
Hi ! @starkgate
I think I figured it out.
The reason of this ValueError on MOT17-05 is that, the image size of MOT17-05 is 640 * 480, which is smaller than 1088 * 800, and this would cause some extreme cases, such as x0 > shape[2] , y0 > shape[3] . Therefore, we need to add some constrains on those extreme cases to fit the rois into images.

By the way, about the resize:
r = r.cpu() * ratio # line 92, tracking_wo_bnw/src/tracktor/reid/resnet.py
Could you please why you add this resizing operation (into 1088 * 800), which has not on the original tracktor?
Many thanks.

**Comment by starkgate** [comment]
Resizing is done by mmdetection in it's train/test pipeline:

```python
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
>>> dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
```

**Comment by Leo63963** [comment]
Hi ! @starkgate
Thanks for your reply.
Yes, I have seen the resizing on mmdetection's testing pipeline.
I am sorry I didn't make it clear.
Could you please tell me, on your code, **reid/resnet.py**:  r = r.cpu() * ratio # line 92
before obtain the cropped image, you resizing the image into 1088 * 800, which may leads to some ValueError when testing on MOT17-05. 
You add it for better Reid performance?
Many thanks.

**Comment by starkgate** [comment]
Ah, the comment is just an example. Basically, the dimensions are multiplied by the ratio / scale_factor that was calculated beforehand. I don't really remember why I had to add this though. I can investigate more tomorrow, in the meantime here's the line where this 'img_metas' is added to the blob if you want to look into it: https://github.com/starkgate/tracking_wo_bnw/blob/1a27f2046ea1068382385800ac1e40489f718752/src/tracktor/tracker.py#L264

mmdetection returns the detections and the preprocessed image + metainformation on the image.

**Comment by starkgate** [comment]
So, the img_metas dictionary is initialized in https://github.com/starkgate/tracking_wo_bnw/blob/1a27f2046ea1068382385800ac1e40489f718752/src/tracktor/model.py#L37

mmdetection applies its transformation pipeline to the image and we store metainformation on the transformations. This metainformation is necessary afterwards in mmdetections `aug_test` function where we only run the RPN and ROIHead part of the network (like in Tracktor) https://github.com/starkgate/tracking_wo_bnw/blob/1a27f2046ea1068382385800ac1e40489f718752/src/tracktor/model.py#L73

This is where it becomes unclear. I'm not sure why, but mmdetection outputs ROIs that are capped at 640x480, as if it didn't take the transformation into account. I double-checked, and the image it's receiving is indeed resized (800x1088 for me). It's quite odd.
That's the reason for the multiplication in https://github.com/starkgate/tracking_wo_bnw/blob/1a27f2046ea1068382385800ac1e40489f718752/src/tracktor/reid/resnet.py#L84, where we use the ratio (ie new image size / old image size) to resize the bboxes to the new image size.

**Comment by starkgate** [comment]
I would certainly be grateful for any insight as to why this happens. Having a third party look at one's code is always profitable

**Comment by Leo63963** [comment]
Hi ! @starkgate 
Thank you so much for your reply.
It is also a great chance for me to learn from your code, and debug and run it.
By the way, the IndexError I encountered was caused by mismatch when tracking, which has been sorted out.
And I will keep updating if I found something interesting.
Many thanks.

**Comment by starkgate** [comment]
> It is also a great chance for me to learn from your code, and debug and run it.

There's no higher compliment than that, thank you. I understand the feeling. It was also a great experience for me to learn from the original code.

Btw, I found where mmdetection rescaled the detection boxes, just setting rescale to False fixes the issue: https://github.com/starkgate/tracking_wo_bnw/blob/41436e06f7bedb9bee5f850fae8395e9716d6a21/src/tracktor/model.py#L57

I've pushed another commit with this change and others that should make the experience of adding a new dataset much clearer. I've removed a lot of redundant code and separated the custom datasets from the MOT one. Not sure if that's useful for you if you're only testing MOT, but it's there :)

**Comment by Leo63963** [comment]
Hi ! @starkgate
Thanks for the reply and update ! I really appreciate it.
The code is working much better, and looks great.
Yeah, I need to add some codes, and make a few changes to make it work for MOT datasets. And I am adding more to make it work on my own datasets as well, based on your code.
Many thanks.
