### ISSUE TITLE
An IndexError

### ISSUE THREAD

**Issue by Leo63963** [starkgate/tracking_wo_bnw#2]
Hi ! @starkgate 

A IndexError happened when tested on MOT17-13:

Traceback (most recent call last):
  File "experiments/scripts/test_tracktor.py", line 106, in <module>
    tracker.step(frame)
  File "/home/lee/Detection/mmdetection/tracking_wo_bnw/src/tracktor/tracker.py", line 300, in step
    person_scores = self.regress_tracks()
  File "/home/lee/Detection/mmdetection/tracking_wo_bnw/src/tracktor/tracker.py", line 86, in regress_tracks
    t.score = scores[i]
IndexError: index 10 is out of bounds for axis 0 with size 10

By debugging, it seems the reason for that is the number of tracks are too small, less than 10.

Do you have any idea about it?

Many thanks.

**Comment by Leo63963** [comment]
Hi !
Update of this bug.
By changing the vaule of detection_nms_thresh, the problem solved sometimes, not always.
And this IndexError happens almost all the time.
IndexError: index xx is out of bounds for axis 0 with size xx. (xx is the number of tracks of current squeence)

Do you have any idea about the reason?
Many thanks.

**Comment by starkgate** [comment]
I really don't know. I didn't touch the `regress_tracks` function Tracktor's code. There should be as many scores as there are tracks, since we're running `predict_boxes` on all recorded tracks through `get_pos`.

**Comment by Leo63963** [comment]
Hi ! @starkgate
Thanks for the reply.
I think the same way, the number of tracks should come from **len(self.tracks)**, which should not lead to this IndexError.
By the way, have you ever tried your code on MOT17 datasets?
I am running it on MOT17 by rewriting some part of the code, but it still does work all the time. Sometime I got some really bad results, which should not happened with changing only default Faster R-CNN into some other detectors from mmdetetion.
Many thanks.

**Comment by starkgate** [comment]
Never tried the MOT datasets. Also why I butchered the code related to it. In retrospect that was a bad idea, but I didn't plan to publish my code when I started working on this.

**Comment by Leo63963** [comment]
Hi ! @starkgate
Thanks for your reply.
I total understand that, and really admire your work.
I will keep debugging and let you know if found anything interesting.
Thanks.

**Comment by Leo63963** [comment]
Hi ! @starkgate
Thanks for your reply.
I totally understand that, and really admire your work.
I will keep debugging and let you know if found anything interesting.
Thanks.
