### ISSUE TITLE
A question about the code

### ISSUE THREAD

**Issue by Leo63963** [starkgate/tracking_wo_bnw#3]
Hi ! @starkgate
I have question about the code, thanks.

On the **model.py**, the function: **predict_boxes()**, line 70, which uses **aug_test()** to regress the roi, should called from **mmdetection/mmdet/models/roi_heads/standard_roi_head.py/aug_test()**, line 264.

It seems that, the function **aug_test()** in your code, called from **mmdetection/mmdet/models/detectors/two_stages.py/aug_test()**, line 201. (maybe not, I am confused)

In my opinion, the difference is, in the first one, the features come from RoIPooling, however, in the second one, the features have to be recalculated (as you comment on your code). The thing is, in the second situation, the proposals of the Tracktor become anchors (which come from RPN) when doing regress, instead of bboxes from last tracks. And it seems in Tracktor, the input of **regress** should be the position of last tracks.

Plus, maybe the **public** detection can be used if we use the **aug_test()** from **standard_roi_head.py**.

I am quite confused with this, could you please tell me that?
Many thanks.

**Comment by starkgate** [comment]
You're completely right. I didn't replicate Tracktor's separation of ROIhead and backbone because of some crashes I was experiencing. But these crashes shouldn't happen with aug_test. I'm not entirely sure how I would modify the code to implement that, did you already look into it?

**Comment by starkgate** [comment]
Right. So this commit should match Tracktor's functionality. It runs, but I'd appreciate feedback on the performance and accuracy of the results!
https://github.com/starkgate/tracking_wo_bnw/commit/9a6a505ce271d408746f1f16c65844b8c0e16df7

I also fixed the crash you were experiencing while tracking. Explanation is here: https://github.com/starkgate/tracking_wo_bnw/blob/9a6a505ce271d408746f1f16c65844b8c0e16df7/src/tracktor/model.py#L28

**Comment by Leo63963** [comment]
Hi ! @starkgate
Thanks for your reply. 
The **model.py** looks great now.
I am not on my lab at present, and I will run and test the new code and provide feedback  as soon as possible.
Thanks for the explanation, which is really helpful. The crash maybe also caused by the usage of different aug_test().

**Comment by Leo63963** [comment]
Hi ! @starkgate 
Sorry for the late response.
I tested on MOT datesets (MOT17-02).

1. About the dimension, as I mentioned before, I encountered dimension mismatch with new code on **src/tracktor/model.py**, which can be solved by revising as follows: 
**line16**: 
detections = self.model.roi_head.simple_test(self.features, proposal_list, self.preprocessed_images['img_metas'][0], rescale=False)[0]
**line 26**:         
detections = self.model.roi_head.simple_test(self.features, proposal_list, self.preprocessed_images['img_metas'][0], rescale=False)[0]
Please note that, this works for me, I am not sure about others since the original version works for you.

2. The crash you explained, which caused by different number of detection (obtained by regression) and input (proposals), is still happen to me, even the **score_thr** on mmdetection is set to 0. By debugging, I found that the detections (regressed from proposals), are less than proposals (normally 1), which means one detection is filtered out, and this should not happened with **score_thr=0**.
Do you have any idea about that?
Many thanks.

**Comment by Leo63963** [comment]
Hi @starkgate 
I think I figure it out.
The crash happened by the difference between the number of detections and proposals, therefore, we should set not only the **score_thr=0**, also **iou_threshold=1.0** in "mmdetection config file", which means all tracks will be regressed and will not be filtered out while detection. The detections should be killed when tracking (following the Tracktor's algorithms).

**Comment by Leo63963** [comment]
Hi ! @starkgate 
Update of the code in terms of performance and accuracy.

1. 

I tested on MOT datasets, and visualize the results, found that the tracking results are extreme bad, with unknown reason.
The thing is, the bounding box is moving, but the boxes are not align with objects.
![000014](https://user-images.githubusercontent.com/48388899/98470471-cab3a200-2220-11eb-8761-1134ba16b35f.jpg)
(Please let me konw if the image is unavaliable).
And I test the dateset with my detector only, it works great.

2.
Plus, I tried to make the code work with all the train MOT sequences, and revised the **src/tracktor/datesets** and  **experiments/scripts/test_tracktor.py**, but meet some unexpected bugs. 
Do you have any idea about that?
Many thanks.

**Comment by Leo63963** [comment]
Hi ! @starkgate 
Update about the bugs.
I revised the code, and it runs with MOT datasets. 

1. On  **src/tracktor/reid/resnet.py:**, I tried to rescale (same with previous code), and it makes no difference, I guess that is the reason why you delete this process in your new code.

2. The tracking results are still bad, almost same with the above image, I guess it might be something wrong with detection. I tried my detector on MOT17, it works well. Therefore, I personally think that, it might be something wrong with **src/tracktor/model.py/detect()**, which is modified from **mmdetection/two_stage.py/simple_test()**.

Do you have any idea?
Many thanks.

**Comment by Leo63963** [comment]
Hi ! @starkgate
Just a thought, which maybe wrong.

In **src/tracktor/model.py**, the function **detect()** and **predict_boxex()**, use **roi_head.simple_test** and **rpn_head.simple_test_rpn** from mmdetection. What if we use **roi_head.aug_test** and **rpn_head.aug_test_rpn**?

The previous version uses aug_test() from two_stage.py, and it works quite well. And based on the performance and visualization, we might need to improve the detection results of the first frame while tracking.
I tried to replace those functions, but failed. Do you think if it will work?

Or maybe we need to do something after obtaining the detection results (bboxes and scores), to make the bboxes align with the detected frame. Perhaps I missed some **post-process** (like decode), which caused the bboxes not align with objects but can still doing tracking, as shown in the above image.

Could you please tell me more about that ? Should it works better?
Many thanks.

**Comment by Leo63963** [comment]
Hi ! @starkgate 
I think I figured it out. It is quite tricky.

In order to solve the problems above, one need to change the **image_scale** of mmdetection while testing. For example, when tested on MOT17 datasets, the default values is 1333 * 800, which is smaller than the image size of MOT17, 1920 * 1080. And if your dateset is smaller than the default values, like 1088 * 800, the default setting would be fine. This might be the reason why the code works for your datasets but not for mine.

And in order to make it work adaptively according to the size of images, we need to set the **rescale=True** in **src/tracktor/model.py**, line 16 and line 26, which enable the detector to rescale the bbox accordingly.

Now the code runs. However, the performance is not so good, which might need to be improved by finding better parameters, such as regression_nms_thresh, detection_nms_thresh and something like that. 

Do you have any suggestion for that?
Thanks.
