### ISSUE TITLE
Update & advice

### ISSUE THREAD

**Issue by Leo63963** [starkgate/tracking_wo_bnw#4]
Hi ! @starkgate 

Based on previous findings, now the code runs, but with bad performance.

In my opinion, in order to make it better, we need to make it match the Tracktor's functionality, as you mentioned before.

Therefore, we may need to do as follows:

1. For **roi_head**, it needs to run with **score_thr=0.0** and **iou_threshold=1.0** while doing regression, to make all the active tracks alive, and then those regressed tracks should be killed based on Tracktor's algorithms.

2.  We also need **another detector** from mmdetection, which could provide detection results of every frame, and then follow the Tracktor's algorithms to be killed or initialized as new tracks. 
The reason for this is that, this detector should function as a private detector, same with **model.py/detect()** in the original Trackor's code. And by doing so, we can perform public detection as well. 
Two detectors from mmdetection working with different settings(score_thr and iou_threshold), so we need two.

What do you think? 
Many thanks.

**Comment by starkgate** [comment]
I think you're definitely on the right track (heh), and I also read your previous message. Unfortunately I don't have the time to look into it right now. If you think you have a solution, feel free to make a pull request!

**Comment by Leo63963** [comment]
Hi ! @starkgate 
Thanks for the reply.
Yeah, I am still trying to make it work better, it does not going well, and I understand that you might busy with papers (good luck).
I will pull request or an issue if I found anything great.
And I would appreciate it if you update and improve this project, since this is your code and it might much easier for you to do so.

Many thanks.

**Comment by Leo63963** [comment]
Hi ! @starkgate 
A quick question, thanks.

By debugging, I found that, the position of active tracks, after regression (**regress_tracks**),  the position has not changed at all, which means, the function **src/tracktor/model.py/predict_boxes()** has not perform regression.

Do you have any idea why?
Many thanks.
